name: Sync Timer Csvfile

on:
  schedule:
  - cron: "*/30 * * * *"
  workflow_dispatch:
      
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Download CSV from Google Sheets
        run: curl -o Serpentgameplay_Timer.csv "https://docs.google.com/spreadsheets/d/1HKpJB5bKrjQFp3OV2pXmnyVTNffAXH1JCL702kDjdEY/export?exportFormat=csv"
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.0.2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: Serpentgameplay_Timer.csv
          username: daanbreur
          repo: cdn
